import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppProvider , AppContext } from "./context/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
       
        <div className="container mx-0 px-4 sm:px-6 lg:px-20" >
      <AppProvider  >
          {children}
      </AppProvider>
          
        </div>
  
      </body>
    </html>
  );
}
